service: dr-watson
frameworkVersion: "3"
provider:
  name: aws
  region: us-east-1
  stage: dev
  runtime: python3.11
  httpApi:
    cors: true
    payload: "2.0"
    disableDefaultEndpoint: false

layers:
  AiResearchLayer:
    path: layers/ai_layers

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - "*.mp3"
    - layers/**
    - "*.ipynb"

functions:
  hello-world:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/hello-world.handler
    timeout: 30
    events:
      - httpApi:
          path: /
          method: GET

  GET-patient:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/GET-patient.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient
          method: GET

  GET-patient-recording-upload-link:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/GET-patient-recording-upload-link.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient/{patientId}/recording
          method: GET

  GET-patient-inital-questions:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/GET-patient-inital-questions.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient/{patientId}/initial-questions
          method: GET

  GET-patient-followup-questions:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/GET-patient-followup-questions.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient/{patientId}/followup-questions
          method: GET

  POST-patient-inital-answer:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/POST-patient-inital-answer.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient/{patientId}/initial-answer
          method: POST

  POST-patient-followup-answer:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/POST-patient-followup-answer.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient/{patientId}/followup-answer
          method: POST

  GET-patient-report:
    layers:
      - { Ref: AiResearchLayerLambdaLayer }
    handler: lambdas/GET-patient-report.handler
    timeout: 30
    events:
      - httpApi:
          path: /patient/{patientId}/report
          method: GET

resources:
  Resources:
    DrWatsonPatientRecordingsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-watson-patient-recordings
